# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliyun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiliguige', models.CharField(blank=True, max_length=50, null=True)),
                ('vcpu', models.CharField(blank=True, max_length=5, null=True)),
                ('neicun_GB', models.CharField(blank=True, max_length=5, null=True)),
                ('anliang_hour', models.CharField(blank=True, max_length=5, null=True)),
                ('biaozhunmuluyuejia', models.CharField(blank=True, max_length=10, null=True)),
                ('youhuiyuejia', models.CharField(blank=True, max_length=10, null=True)),
                ('nianfuyuejia', models.CharField(blank=True, max_length=10, null=True)),
                ('sannianfuyuejia', models.CharField(blank=True, max_length=10, null=True)),
                ('wunianfuyuejia', models.CharField(blank=True, max_length=10, null=True)),
                ('jiagediyu', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
